services:
    web:
        build: .
        ports: 
            - "5000:5000"
        links:
            - "database:fmc_db"
        depends_on:
            - database
    database:
        image: mysql:8.0.24
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
        command: --default-authentication-plugin=mysql_native_password
        volumes: 
            - ./database.sql:/docker-entrypoint-initdb.d/database.sql        